In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

In [2]:
#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Reading the dataset and viewing head and tail
df = pd.read_excel('Health Insurance Dataset.xlsx', skiprows=0, nrows=1338)
df

,age,sex,bmi,children,smoker,region,charges,Level,score
0,19,female,27.900,0,yes,southwest,16884.92400,B,72
1,18,male,33.770,1,no,southeast,1725.55230,C,69
2,28,male,33.000,3,no,southeast,4449.46200,B,90
3,33,male,22.705,0,no,northwest,21984.47061,A,47
4,32,male,28.880,0,no,northwest,3866.85520,C,76
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,B,90
1334,18,female,31.920,0,no,northeast,2205.98080,C,83
1335,18,female,36.850,0,no,southeast,1629.83350,B,61
1336,21,female,25.800,0,no,southwest,2007.94500,D,76
1337,61,female,29.070,0,yes,northwest,29141.36030,C,49

#### Parametric (t_statistic) test

In [7]:
# Research question - Does smokers have different BMI than non-smokers?
# H0: There is no difference in BMI between smoker and non-smoker.
# H1: There is a difference in BMI between smoker and non-smoker. 

import scipy.stats as stats

df_smoker_bmi = df.loc[df['smoker'] == 'yes', 'bmi'].tolist()
df_nonsmoker_bmi = df.loc[df['smoker'] == 'no', 'bmi'].tolist()

t_stat, p_value = stats.ttest_ind(df_smoker_bmi, df_nonsmoker_bmi, equal_var=True) #t-test w/equal variance between smokers and non-smokers

print('t_stat', t_stat)
print('p_value', p_value)
print('threshold 0.05')

if p_value < 0.05:
    print("There is a statistically significant difference thus we reject the null hypothesis.")
else:
    print("There is no statistically significant difference thus we fail to reject the null hypothesis")
    

#since p-value came much greater than the statistical significance threshold of 0.05, then there is no difference in BMI between smoker and nonsmoker
#t_stat is also very closer to zero thus the difference between these two groups is very small 

# now, question is raised, is smoking really the variable that effects BMI? According to this test, no. And in order to improve
# perhaps utilizing Multiple Linear Regression that takes into account all other columns/variables in the dataset

t_stat 0.13708403310827058
p_value 0.8909850280013041
threshold 0.05
There is no statistically significant difference thus we fail to reject the null hypothesis

#### Nonparametric (chi_square) test

In [9]:
# Research question - Is there association between Sex and Smoker?
# H0: Sex and Smoker have no relationship
# H1: Sex and Smoker they do have relationship 

from scipy.stats import chi2_contingency

contingency_table = pd.crosstab(df['sex'], df['smoker'])

chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print('chi2_test', chi2)
print('p_value', p_value)
print('Degrees of Freedom:', dof)
#print('Expected Frequency', expected)
print('threshold 0.05')

if p_value < 0.05:
    print("There is a statistically significant relationship between Sex and Smoker, thus we reject the null hypothesis")
else:
    print("There is no statistically significant relationship between Sex and Smoker, thus fail to reject the null hypothesis.")
    

#since p_value came less than the set threshold, this tell us that there is relationship between gender and smoker. 
# also looking at the proportions, there is higher proportion of being male smoker than a female

# now, question is raised - how strong is this relationship between sex and smoker. Chi-square test doesn't give us that. It just tells us
# that there is a relationship. To calculate the strength there are other type of tests out there.

chi2_test 7.39291081459996
p_value 0.006548143503580696
Degrees of Freedom: 1
threshold 0.05
There is a statistically significant relationship between Sex and Smoker, thus we reject the null hypothesis

In [10]:
contingency_table

smoker   no  yes
sex
female  547  115
male    517  159

In [11]:
print((115/(547+115))*100)
print((159/(517+159))*100)

#the propotions of smoker patients seem higher on male than female.

17.371601208459214
23.5207100591716